[project]
name = "my-viewer"
version = "0.1.0"
description = ""
authors = [
    {name = "ALQ78",email = "ALQ78@users.noreply.github.com"}
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy (>=2.3.3,<3.0.0)",
    "pyqtgraph (>=0.13.7,<0.14.0)",
    "pyqt5 (>=5.15.11,<6.0.0)"
]

[tool.poetry]
packages = [{include = "my_viewer", from = "src"}]

repository = "https://github.com/ALQ78/mon-projet"
homepage = "https://github.com/ALQ78/mon-projet"
documentation = "https://github.com/TonUtilisateur/mon-projet/wiki"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-mock = "^3.15.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
